/* eslint object-curly-newline: ["error", "never"] */
/* eslint-env es6 */
const mongoose = require('mongoose');
const Product = require('./productModel');
const ENV = require('../config');

// const DB_PATH = `mongodb://${ENV.dbUser}:${ENV.dbPass}@${ENV.dbHost}:${ENV.dbPort}/${ENV.dbName}`;
const DB_PATH = ENV.dbLong;

const REVIEWS = [
  { product_id: 1, overall_rating: 3 },
  { product_id: 1, overall_rating: 4 },
  { product_id: 1, overall_rating: 2 },
  { product_id: 1, overall_rating: 1 },
  { product_id: 1, overall_rating: 5 },
  { product_id: 2, overall_rating: 3 },
  { product_id: 2, overall_rating: 2 },
  { product_id: 2, overall_rating: 5 },
  { product_id: 2, overall_rating: 2 },
  { product_id: 2, overall_rating: 5 },
  { product_id: 3, overall_rating: 4 },
  { product_id: 3, overall_rating: 2 },
  { product_id: 3, overall_rating: 3 },
  { product_id: 3, overall_rating: 2 },
  { product_id: 3, overall_rating: 5 },
  { product_id: 4, overall_rating: 5 },
  { product_id: 4, overall_rating: 4 },
  { product_id: 4, overall_rating: 5 },
  { product_id: 4, overall_rating: 4 },
  { product_id: 4, overall_rating: 5 },
  { product_id: 5, overall_rating: 2 },
  { product_id: 5, overall_rating: 5 },
  { product_id: 5, overall_rating: 5 },
  { product_id: 5, overall_rating: 4 },
  { product_id: 5, overall_rating: 2 },
  { product_id: 6, overall_rating: 2 },
  { product_id: 6, overall_rating: 4 },
  { product_id: 6, overall_rating: 1 },
  { product_id: 6, overall_rating: 3 },
  { product_id: 6, overall_rating: 2 },
  { product_id: 7, overall_rating: 5 },
  { product_id: 7, overall_rating: 5 },
  { product_id: 7, overall_rating: 2 },
  { product_id: 7, overall_rating: 5 },
  { product_id: 7, overall_rating: 4 },
  { product_id: 8, overall_rating: 5 },
  { product_id: 8, overall_rating: 2 },
  { product_id: 8, overall_rating: 5 },
  { product_id: 8, overall_rating: 4 },
  { product_id: 8, overall_rating: 1 },
  { product_id: 9, overall_rating: 2 },
  { product_id: 9, overall_rating: 2 },
  { product_id: 9, overall_rating: 2 },
  { product_id: 9, overall_rating: 4 },
  { product_id: 9, overall_rating: 3 },
  { product_id: 10, overall_rating: 5 },
  { product_id: 10, overall_rating: 3 },
  { product_id: 10, overall_rating: 4 },
  { product_id: 10, overall_rating: 2 },
  { product_id: 10, overall_rating: 3 },
  { product_id: 11, overall_rating: 3 },
  { product_id: 11, overall_rating: 2 },
  { product_id: 11, overall_rating: 4 },
  { product_id: 11, overall_rating: 5 },
  { product_id: 11, overall_rating: 5 },
  { product_id: 12, overall_rating: 2 },
  { product_id: 12, overall_rating: 3 },
  { product_id: 12, overall_rating: 1 },
  { product_id: 12, overall_rating: 2 },
  { product_id: 12, overall_rating: 5 },
  { product_id: 13, overall_rating: 2 },
  { product_id: 13, overall_rating: 5 },
  { product_id: 13, overall_rating: 5 },
  { product_id: 13, overall_rating: 3 },
  { product_id: 13, overall_rating: 5 },
  { product_id: 14, overall_rating: 4 },
  { product_id: 14, overall_rating: 4 },
  { product_id: 14, overall_rating: 2 },
  { product_id: 14, overall_rating: 5 },
  { product_id: 14, overall_rating: 5 },
  { product_id: 15, overall_rating: 3 },
  { product_id: 15, overall_rating: 4 },
  { product_id: 15, overall_rating: 5 },
  { product_id: 15, overall_rating: 5 },
  { product_id: 15, overall_rating: 5 },
  { product_id: 16, overall_rating: 2 },
  { product_id: 16, overall_rating: 5 },
  { product_id: 16, overall_rating: 3 },
  { product_id: 16, overall_rating: 5 },
  { product_id: 16, overall_rating: 1 },
  { product_id: 17, overall_rating: 4 },
  { product_id: 17, overall_rating: 5 },
  { product_id: 17, overall_rating: 5 },
  { product_id: 17, overall_rating: 5 },
  { product_id: 17, overall_rating: 4 },
  { product_id: 18, overall_rating: 4 },
  { product_id: 18, overall_rating: 2 },
  { product_id: 18, overall_rating: 2 },
  { product_id: 18, overall_rating: 5 },
  { product_id: 18, overall_rating: 5 },
  { product_id: 19, overall_rating: 3 },
  { product_id: 19, overall_rating: 5 },
  { product_id: 19, overall_rating: 2 },
  { product_id: 19, overall_rating: 4 },
  { product_id: 19, overall_rating: 5 },
  { product_id: 20, overall_rating: 3 },
  { product_id: 20, overall_rating: 2 },
  { product_id: 20, overall_rating: 3 },
  { product_id: 20, overall_rating: 4 },
  { product_id: 20, overall_rating: 5 },
  { product_id: 21, overall_rating: 5 },
  { product_id: 21, overall_rating: 4 },
  { product_id: 21, overall_rating: 2 },
  { product_id: 21, overall_rating: 5 },
  { product_id: 21, overall_rating: 3 },
  { product_id: 22, overall_rating: 2 },
  { product_id: 22, overall_rating: 4 },
  { product_id: 22, overall_rating: 5 },
  { product_id: 22, overall_rating: 2 },
  { product_id: 22, overall_rating: 5 },
  { product_id: 23, overall_rating: 3 },
  { product_id: 23, overall_rating: 3 },
  { product_id: 23, overall_rating: 2 },
  { product_id: 23, overall_rating: 5 },
  { product_id: 23, overall_rating: 5 },
  { product_id: 24, overall_rating: 5 },
  { product_id: 24, overall_rating: 5 },
  { product_id: 24, overall_rating: 5 },
  { product_id: 24, overall_rating: 2 },
  { product_id: 24, overall_rating: 2 },
  { product_id: 25, overall_rating: 2 },
  { product_id: 25, overall_rating: 5 },
  { product_id: 25, overall_rating: 5 },
  { product_id: 25, overall_rating: 3 },
  { product_id: 25, overall_rating: 4 },
  { product_id: 26, overall_rating: 3 },
  { product_id: 26, overall_rating: 5 },
  { product_id: 26, overall_rating: 4 },
  { product_id: 26, overall_rating: 5 },
  { product_id: 26, overall_rating: 3 },
  { product_id: 27, overall_rating: 2 },
  { product_id: 27, overall_rating: 5 },
  { product_id: 27, overall_rating: 5 },
  { product_id: 27, overall_rating: 1 },
  { product_id: 27, overall_rating: 4 },
  { product_id: 28, overall_rating: 5 },
  { product_id: 28, overall_rating: 4 },
  { product_id: 28, overall_rating: 4 },
  { product_id: 28, overall_rating: 5 },
  { product_id: 28, overall_rating: 5 },
  { product_id: 29, overall_rating: 2 },
  { product_id: 29, overall_rating: 4 },
  { product_id: 29, overall_rating: 4 },
  { product_id: 29, overall_rating: 5 },
  { product_id: 29, overall_rating: 2 },
  { product_id: 30, overall_rating: 1 },
  { product_id: 30, overall_rating: 5 },
  { product_id: 30, overall_rating: 5 },
  { product_id: 30, overall_rating: 4 },
  { product_id: 30, overall_rating: 3 },
  { product_id: 31, overall_rating: 5 },
  { product_id: 31, overall_rating: 2 },
  { product_id: 31, overall_rating: 4 },
  { product_id: 31, overall_rating: 2 },
  { product_id: 31, overall_rating: 5 },
  { product_id: 32, overall_rating: 5 },
  { product_id: 32, overall_rating: 4 },
  { product_id: 32, overall_rating: 3 },
  { product_id: 32, overall_rating: 4 },
  { product_id: 32, overall_rating: 1 },
  { product_id: 33, overall_rating: 5 },
  { product_id: 33, overall_rating: 5 },
  { product_id: 33, overall_rating: 5 },
  { product_id: 33, overall_rating: 2 },
  { product_id: 33, overall_rating: 3 },
  { product_id: 34, overall_rating: 3 },
  { product_id: 34, overall_rating: 4 },
  { product_id: 34, overall_rating: 1 },
  { product_id: 34, overall_rating: 5 },
  { product_id: 34, overall_rating: 4 },
  { product_id: 35, overall_rating: 4 },
  { product_id: 35, overall_rating: 4 },
  { product_id: 35, overall_rating: 5 },
  { product_id: 35, overall_rating: 2 },
  { product_id: 35, overall_rating: 3 },
  { product_id: 36, overall_rating: 3 },
  { product_id: 36, overall_rating: 5 },
  { product_id: 36, overall_rating: 5 },
  { product_id: 36, overall_rating: 2 },
  { product_id: 36, overall_rating: 4 },
  { product_id: 37, overall_rating: 4 },
  { product_id: 37, overall_rating: 5 },
  { product_id: 37, overall_rating: 5 },
  { product_id: 37, overall_rating: 2 },
  { product_id: 37, overall_rating: 5 },
  { product_id: 38, overall_rating: 5 },
  { product_id: 38, overall_rating: 5 },
  { product_id: 38, overall_rating: 3 },
  { product_id: 38, overall_rating: 5 },
  { product_id: 38, overall_rating: 1 },
  { product_id: 39, overall_rating: 3 },
  { product_id: 39, overall_rating: 5 },
  { product_id: 39, overall_rating: 5 },
  { product_id: 39, overall_rating: 2 },
  { product_id: 39, overall_rating: 5 },
  { product_id: 40, overall_rating: 5 },
  { product_id: 40, overall_rating: 2 },
  { product_id: 40, overall_rating: 5 },
  { product_id: 40, overall_rating: 5 },
  { product_id: 40, overall_rating: 4 },
  { product_id: 41, overall_rating: 5 },
  { product_id: 41, overall_rating: 4 },
  { product_id: 41, overall_rating: 4 },
  { product_id: 41, overall_rating: 5 },
  { product_id: 41, overall_rating: 3 },
  { product_id: 42, overall_rating: 4 },
  { product_id: 42, overall_rating: 2 },
  { product_id: 42, overall_rating: 2 },
  { product_id: 42, overall_rating: 4 },
  { product_id: 42, overall_rating: 1 },
  { product_id: 43, overall_rating: 4 },
  { product_id: 43, overall_rating: 5 },
  { product_id: 43, overall_rating: 4 },
  { product_id: 43, overall_rating: 5 },
  { product_id: 43, overall_rating: 2 },
  { product_id: 44, overall_rating: 5 },
  { product_id: 44, overall_rating: 4 },
  { product_id: 44, overall_rating: 5 },
  { product_id: 44, overall_rating: 1 },
  { product_id: 44, overall_rating: 5 },
  { product_id: 45, overall_rating: 3 },
  { product_id: 45, overall_rating: 4 },
  { product_id: 45, overall_rating: 2 },
  { product_id: 45, overall_rating: 4 },
  { product_id: 45, overall_rating: 2 },
  { product_id: 46, overall_rating: 4 },
  { product_id: 46, overall_rating: 2 },
  { product_id: 46, overall_rating: 5 },
  { product_id: 46, overall_rating: 2 },
  { product_id: 46, overall_rating: 3 },
  { product_id: 47, overall_rating: 5 },
  { product_id: 47, overall_rating: 2 },
  { product_id: 47, overall_rating: 4 },
  { product_id: 47, overall_rating: 5 },
  { product_id: 47, overall_rating: 4 },
  { product_id: 48, overall_rating: 5 },
  { product_id: 48, overall_rating: 2 },
  { product_id: 48, overall_rating: 4 },
  { product_id: 48, overall_rating: 5 },
  { product_id: 48, overall_rating: 1 },
  { product_id: 49, overall_rating: 1 },
  { product_id: 49, overall_rating: 5 },
  { product_id: 49, overall_rating: 2 },
  { product_id: 49, overall_rating: 4 },
  { product_id: 49, overall_rating: 5 },
  { product_id: 50, overall_rating: 5 },
  { product_id: 50, overall_rating: 5 },
  { product_id: 50, overall_rating: 4 },
  { product_id: 50, overall_rating: 3 },
  { product_id: 50, overall_rating: 5 },
  { product_id: 51, overall_rating: 5 },
  { product_id: 51, overall_rating: 5 },
  { product_id: 51, overall_rating: 3 },
  { product_id: 51, overall_rating: 2 },
  { product_id: 51, overall_rating: 4 },
  { product_id: 52, overall_rating: 2 },
  { product_id: 52, overall_rating: 4 },
  { product_id: 52, overall_rating: 3 },
  { product_id: 52, overall_rating: 5 },
  { product_id: 52, overall_rating: 1 },
  { product_id: 53, overall_rating: 2 },
  { product_id: 53, overall_rating: 5 },
  { product_id: 53, overall_rating: 5 },
  { product_id: 53, overall_rating: 3 },
  { product_id: 53, overall_rating: 4 },
  { product_id: 54, overall_rating: 4 },
  { product_id: 54, overall_rating: 5 },
  { product_id: 54, overall_rating: 5 },
  { product_id: 54, overall_rating: 4 },
  { product_id: 54, overall_rating: 2 },
  { product_id: 55, overall_rating: 4 },
  { product_id: 55, overall_rating: 4 },
  { product_id: 55, overall_rating: 5 },
  { product_id: 55, overall_rating: 5 },
  { product_id: 55, overall_rating: 5 },
  { product_id: 56, overall_rating: 5 },
  { product_id: 56, overall_rating: 5 },
  { product_id: 56, overall_rating: 2 },
  { product_id: 56, overall_rating: 4 },
  { product_id: 56, overall_rating: 2 },
  { product_id: 57, overall_rating: 5 },
  { product_id: 57, overall_rating: 5 },
  { product_id: 57, overall_rating: 2 },
  { product_id: 57, overall_rating: 3 },
  { product_id: 57, overall_rating: 4 },
  { product_id: 58, overall_rating: 1 },
  { product_id: 58, overall_rating: 4 },
  { product_id: 58, overall_rating: 4 },
  { product_id: 58, overall_rating: 5 },
  { product_id: 58, overall_rating: 3 },
  { product_id: 59, overall_rating: 5 },
  { product_id: 59, overall_rating: 4 },
  { product_id: 59, overall_rating: 2 },
  { product_id: 59, overall_rating: 5 },
  { product_id: 59, overall_rating: 2 },
  { product_id: 60, overall_rating: 4 },
  { product_id: 60, overall_rating: 3 },
  { product_id: 60, overall_rating: 2 },
  { product_id: 60, overall_rating: 5 },
  { product_id: 60, overall_rating: 3 },
  { product_id: 61, overall_rating: 2 },
  { product_id: 61, overall_rating: 2 },
  { product_id: 61, overall_rating: 3 },
  { product_id: 61, overall_rating: 5 },
  { product_id: 61, overall_rating: 4 },
  { product_id: 62, overall_rating: 5 },
  { product_id: 62, overall_rating: 1 },
  { product_id: 62, overall_rating: 3 },
  { product_id: 62, overall_rating: 2 },
  { product_id: 62, overall_rating: 2 },
  { product_id: 63, overall_rating: 4 },
  { product_id: 63, overall_rating: 5 },
  { product_id: 63, overall_rating: 5 },
  { product_id: 63, overall_rating: 4 },
  { product_id: 63, overall_rating: 2 },
  { product_id: 64, overall_rating: 4 },
  { product_id: 64, overall_rating: 5 },
  { product_id: 64, overall_rating: 2 },
  { product_id: 64, overall_rating: 4 },
  { product_id: 64, overall_rating: 5 },
  { product_id: 65, overall_rating: 4 },
  { product_id: 65, overall_rating: 1 },
  { product_id: 65, overall_rating: 3 },
  { product_id: 65, overall_rating: 4 },
  { product_id: 65, overall_rating: 5 },
  { product_id: 66, overall_rating: 3 },
  { product_id: 66, overall_rating: 2 },
  { product_id: 66, overall_rating: 2 },
  { product_id: 66, overall_rating: 5 },
  { product_id: 66, overall_rating: 2 },
  { product_id: 67, overall_rating: 4 },
  { product_id: 67, overall_rating: 2 },
  { product_id: 67, overall_rating: 5 },
  { product_id: 67, overall_rating: 5 },
  { product_id: 67, overall_rating: 3 },
  { product_id: 68, overall_rating: 5 },
  { product_id: 68, overall_rating: 1 },
  { product_id: 68, overall_rating: 2 },
  { product_id: 68, overall_rating: 5 },
  { product_id: 68, overall_rating: 4 },
  { product_id: 69, overall_rating: 4 },
  { product_id: 69, overall_rating: 3 },
  { product_id: 69, overall_rating: 5 },
  { product_id: 69, overall_rating: 2 },
  { product_id: 69, overall_rating: 1 },
  { product_id: 70, overall_rating: 5 },
  { product_id: 70, overall_rating: 2 },
  { product_id: 70, overall_rating: 4 },
  { product_id: 70, overall_rating: 5 },
  { product_id: 70, overall_rating: 2 },
  { product_id: 71, overall_rating: 4 },
  { product_id: 71, overall_rating: 2 },
  { product_id: 71, overall_rating: 5 },
  { product_id: 71, overall_rating: 5 },
  { product_id: 71, overall_rating: 4 },
  { product_id: 72, overall_rating: 2 },
  { product_id: 72, overall_rating: 4 },
  { product_id: 72, overall_rating: 5 },
  { product_id: 72, overall_rating: 4 },
  { product_id: 72, overall_rating: 2 },
  { product_id: 73, overall_rating: 5 },
  { product_id: 73, overall_rating: 5 },
  { product_id: 73, overall_rating: 2 },
  { product_id: 73, overall_rating: 4 },
  { product_id: 73, overall_rating: 3 },
  { product_id: 74, overall_rating: 5 },
  { product_id: 74, overall_rating: 3 },
  { product_id: 74, overall_rating: 2 },
  { product_id: 74, overall_rating: 4 },
  { product_id: 74, overall_rating: 4 },
  { product_id: 75, overall_rating: 5 },
  { product_id: 75, overall_rating: 2 },
  { product_id: 75, overall_rating: 5 },
  { product_id: 75, overall_rating: 2 },
  { product_id: 75, overall_rating: 5 },
  { product_id: 76, overall_rating: 4 },
  { product_id: 76, overall_rating: 5 },
  { product_id: 76, overall_rating: 5 },
  { product_id: 76, overall_rating: 3 },
  { product_id: 76, overall_rating: 3 },
  { product_id: 77, overall_rating: 5 },
  { product_id: 77, overall_rating: 2 },
  { product_id: 77, overall_rating: 4 },
  { product_id: 77, overall_rating: 1 },
  { product_id: 77, overall_rating: 5 },
  { product_id: 78, overall_rating: 3 },
  { product_id: 78, overall_rating: 5 },
  { product_id: 78, overall_rating: 2 },
  { product_id: 78, overall_rating: 5 },
  { product_id: 78, overall_rating: 5 },
  { product_id: 79, overall_rating: 5 },
  { product_id: 79, overall_rating: 5 },
  { product_id: 79, overall_rating: 2 },
  { product_id: 79, overall_rating: 1 },
  { product_id: 79, overall_rating: 5 },
  { product_id: 80, overall_rating: 2 },
  { product_id: 80, overall_rating: 2 },
  { product_id: 80, overall_rating: 4 },
  { product_id: 80, overall_rating: 2 },
  { product_id: 80, overall_rating: 4 },
  { product_id: 81, overall_rating: 4 },
  { product_id: 81, overall_rating: 5 },
  { product_id: 81, overall_rating: 5 },
  { product_id: 81, overall_rating: 1 },
  { product_id: 81, overall_rating: 5 },
  { product_id: 82, overall_rating: 2 },
  { product_id: 82, overall_rating: 5 },
  { product_id: 82, overall_rating: 4 },
  { product_id: 82, overall_rating: 2 },
  { product_id: 82, overall_rating: 3 },
  { product_id: 83, overall_rating: 5 },
  { product_id: 83, overall_rating: 4 },
  { product_id: 83, overall_rating: 5 },
  { product_id: 83, overall_rating: 3 },
  { product_id: 83, overall_rating: 5 },
  { product_id: 84, overall_rating: 3 },
  { product_id: 84, overall_rating: 4 },
  { product_id: 84, overall_rating: 4 },
  { product_id: 84, overall_rating: 5 },
  { product_id: 84, overall_rating: 5 },
  { product_id: 85, overall_rating: 5 },
  { product_id: 85, overall_rating: 3 },
  { product_id: 85, overall_rating: 2 },
  { product_id: 85, overall_rating: 5 },
  { product_id: 85, overall_rating: 5 },
  { product_id: 86, overall_rating: 5 },
  { product_id: 86, overall_rating: 3 },
  { product_id: 86, overall_rating: 5 },
  { product_id: 86, overall_rating: 4 },
  { product_id: 86, overall_rating: 2 },
  { product_id: 87, overall_rating: 2 },
  { product_id: 87, overall_rating: 2 },
  { product_id: 87, overall_rating: 2 },
  { product_id: 87, overall_rating: 5 },
  { product_id: 87, overall_rating: 5 },
  { product_id: 88, overall_rating: 3 },
  { product_id: 88, overall_rating: 5 },
  { product_id: 88, overall_rating: 4 },
  { product_id: 88, overall_rating: 2 },
  { product_id: 88, overall_rating: 1 },
  { product_id: 88, overall_rating: 1 },
  { product_id: 89, overall_rating: 2 },
  { product_id: 89, overall_rating: 5 },
  { product_id: 89, overall_rating: 5 },
  { product_id: 89, overall_rating: 4 },
  { product_id: 90, overall_rating: 4 },
  { product_id: 90, overall_rating: 2 },
  { product_id: 90, overall_rating: 1 },
  { product_id: 90, overall_rating: 5 },
  { product_id: 90, overall_rating: 4 },
  { product_id: 91, overall_rating: 4 },
  { product_id: 91, overall_rating: 5 },
  { product_id: 91, overall_rating: 4 },
  { product_id: 91, overall_rating: 5 },
  { product_id: 91, overall_rating: 2 },
  { product_id: 92, overall_rating: 5 },
  { product_id: 92, overall_rating: 3 },
  { product_id: 92, overall_rating: 5 },
  { product_id: 92, overall_rating: 1 },
  { product_id: 92, overall_rating: 4 },
  { product_id: 93, overall_rating: 5 },
  { product_id: 93, overall_rating: 5 },
  { product_id: 93, overall_rating: 2 },
  { product_id: 93, overall_rating: 5 },
  { product_id: 93, overall_rating: 2 },
  { product_id: 94, overall_rating: 2 },
  { product_id: 94, overall_rating: 1 },
  { product_id: 94, overall_rating: 5 },
  { product_id: 94, overall_rating: 4 },
  { product_id: 94, overall_rating: 5 },
  { product_id: 95, overall_rating: 4 },
  { product_id: 95, overall_rating: 5 },
  { product_id: 95, overall_rating: 2 },
  { product_id: 95, overall_rating: 5 },
  { product_id: 95, overall_rating: 5 },
  { product_id: 96, overall_rating: 5 },
  { product_id: 96, overall_rating: 2 },
  { product_id: 96, overall_rating: 5 },
  { product_id: 96, overall_rating: 5 },
  { product_id: 96, overall_rating: 1 },
  { product_id: 97, overall_rating: 5 },
  { product_id: 97, overall_rating: 4 },
  { product_id: 97, overall_rating: 2 },
  { product_id: 97, overall_rating: 4 },
  { product_id: 97, overall_rating: 5 },
  { product_id: 98, overall_rating: 1 },
  { product_id: 98, overall_rating: 2 },
  { product_id: 98, overall_rating: 5 },
  { product_id: 98, overall_rating: 3 },
  { product_id: 98, overall_rating: 3 },
  { product_id: 99, overall_rating: 5 },
  { product_id: 99, overall_rating: 4 },
  { product_id: 99, overall_rating: 2 },
  { product_id: 99, overall_rating: 5 },
  { product_id: 99, overall_rating: 2 },
  { product_id: 100, overall_rating: 4 },
  { product_id: 100, overall_rating: 5 },
  { product_id: 100, overall_rating: 5 },
  { product_id: 100, overall_rating: 5 },
  { product_id: 100, overall_rating: 2 },
];

mongoose.connect(DB_PATH, { useNewUrlParser: true, useUnifiedTopology: true });

const buildReviewData = (data) => {
  const reviews = {};
  for (let i = 0; i < data.length; i += 1) {
    const id = data[i].product_id;
    reviews[id] = reviews[id] || {};
    reviews[id].count = reviews[id].count + 1 || 1;
    reviews[id].total = reviews[id].total + data[i].overall_rating || data[i].overall_rating;
    reviews[id].average = reviews[id].total / reviews[id].count || 0;
  }
  return reviews;
};

const REVIEW_DATA = buildReviewData(REVIEWS);

const getRandomIdsWithin = (min, max, id, count = 12) => {
  const output = [];
  const range = max - min;
  for (let i = 0; i < count; i += 1) {
    const rand = Math.round(Math.random() * range) + min;
    if (rand === id || output.includes(rand)) {
      i -= 1;
    } else {
      output.push(rand);
    }
  }
  return output;
};

const closeGen = (id) => {
  const min = Math.floor((id / 20) - 0.01) * 20;
  const max = Math.ceil(id / 20) * 20;
  return getRandomIdsWithin(min, max, id);
};

const looseGen = (id) => getRandomIdsWithin(1, 100, id, 11).concat([81]);

const imgStr = (id) => `${id.toString().padStart(3, '0')}.webp`;

Product.bulkWrite([
  { replaceOne: { filter: { id: 1 }, upsert: true, replacement: { name: 'ANTILOP', description: 'High chair with tray, silver color white, silver color', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 1, rating: REVIEW_DATA[1].average, reviews: REVIEW_DATA[1].count, image: imgStr(1), close: closeGen(1), loose: looseGen(1) } } },
  { replaceOne: { filter: { id: 2 }, upsert: true, replacement: { name: 'TOBIAS', description: 'Chair, clear, chrome plated', price: 79.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 2, rating: REVIEW_DATA[2].average, reviews: REVIEW_DATA[2].count, image: imgStr(2), close: closeGen(2), loose: looseGen(2) } } },
  { replaceOne: { filter: { id: 3 }, upsert: true, replacement: { name: 'HAVSTEN', description: 'Chair, in/outdoor, beige, 32 5/8x37x35 3/8 "', price: 260.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 3, rating: REVIEW_DATA[3].average, reviews: REVIEW_DATA[3].count, image: imgStr(3), close: closeGen(3), loose: looseGen(3) } } },
  { replaceOne: { filter: { id: 4 }, upsert: true, replacement: { name: 'GLENN', description: 'Bar stool, white, chrome plated, 26 "', price: 79.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 4, rating: REVIEW_DATA[4].average, reviews: REVIEW_DATA[4].count, image: imgStr(4), close: closeGen(4), loose: looseGen(4) } } },
  { replaceOne: { filter: { id: 5 }, upsert: true, replacement: { name: 'FRANKLIN', description: 'Bar stool with backrest, foldable, white, white, 24 3/4 "', price: 29.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 5, rating: REVIEW_DATA[5].average, reviews: REVIEW_DATA[5].count, image: imgStr(5), close: closeGen(5), loose: looseGen(5) } } },
  { replaceOne: { filter: { id: 6 }, upsert: true, replacement: { name: 'JULES', description: 'Child\'s desk chair, white', price: 34.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 6, rating: REVIEW_DATA[6].average, reviews: REVIEW_DATA[6].count, image: imgStr(6), close: closeGen(6), loose: looseGen(6) } } },
  { replaceOne: { filter: { id: 7 }, upsert: true, replacement: { name: 'ÖRFJÄLL', description: 'Swivel chair, white, Vissle blue', price: 49.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 7, rating: REVIEW_DATA[7].average, reviews: REVIEW_DATA[7].count, image: imgStr(7), close: closeGen(7), loose: looseGen(7) } } },
  { replaceOne: { filter: { id: 8 }, upsert: true, replacement: { name: 'GRÖNADAL', description: 'Rocking chair, gray, natural', price: 249.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 8, rating: REVIEW_DATA[8].average, reviews: REVIEW_DATA[8].count, image: imgStr(8), close: closeGen(8), loose: looseGen(8) } } },
  { replaceOne: { filter: { id: 9 }, upsert: true, replacement: { name: 'VÅGSBERG / SPORREN', description: 'Swivel chair, black', price: 49.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 9, rating: REVIEW_DATA[9].average, reviews: REVIEW_DATA[9].count, image: imgStr(9), close: closeGen(9), loose: looseGen(9) } } },
  { replaceOne: { filter: { id: 10 }, upsert: true, replacement: { name: 'DIETMAR', description: 'Underframe for armchair, chrome plated', price: 40.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 10, rating: REVIEW_DATA[10].average, reviews: REVIEW_DATA[10].count, image: imgStr(10), close: closeGen(10), loose: looseGen(10) } } },
  { replaceOne: { filter: { id: 11 }, upsert: true, replacement: { name: 'LANGUR', description: 'High chair tray, white', price: 10.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 11, rating: REVIEW_DATA[11].average, reviews: REVIEW_DATA[11].count, image: imgStr(11), close: closeGen(11), loose: looseGen(11) } } },
  { replaceOne: { filter: { id: 12 }, upsert: true, replacement: { name: 'JOKKMOKK', description: 'Table and 4 chairs, antique stain', price: 129.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 12, rating: REVIEW_DATA[12].average, reviews: REVIEW_DATA[12].count, image: imgStr(12), close: closeGen(12), loose: looseGen(12) } } },
  { replaceOne: { filter: { id: 13 }, upsert: true, replacement: { name: 'STEFAN', description: 'Chair, brown-black', price: 25.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 13, rating: REVIEW_DATA[13].average, reviews: REVIEW_DATA[13].count, image: imgStr(13), close: closeGen(13), loose: looseGen(13) } } },
  { replaceOne: { filter: { id: 14 }, upsert: true, replacement: { name: 'BALTSAR', description: 'Chair, black-blue, brown', price: 169.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 14, rating: REVIEW_DATA[14].average, reviews: REVIEW_DATA[14].count, image: imgStr(14), close: closeGen(14), loose: looseGen(14) } } },
  { replaceOne: { filter: { id: 15 }, upsert: true, replacement: { name: 'HARRY', description: 'Chair, black, Knisa light gray', price: 55.00, isOnSale: true, isFamilyPriced: false, isNewItem: true, hasOptions: false, id: 15, rating: REVIEW_DATA[15].average, reviews: REVIEW_DATA[15].count, image: imgStr(15), close: closeGen(15), loose: looseGen(15) } } },
  { replaceOne: { filter: { id: 16 }, upsert: true, replacement: { name: 'MARIUS', description: 'Stool, black', price: 5.99, isOnSale: true, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 16, rating: REVIEW_DATA[16].average, reviews: REVIEW_DATA[16].count, image: imgStr(16), close: closeGen(16), loose: looseGen(16) } } },
  { replaceOne: { filter: { id: 17 }, upsert: true, replacement: { name: 'MARTIN', description: 'Chair, black, black', price: 19.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 17, rating: REVIEW_DATA[17].average, reviews: REVIEW_DATA[17].count, image: imgStr(17), close: closeGen(17), loose: looseGen(17) } } },
  { replaceOne: { filter: { id: 18 }, upsert: true, replacement: { name: 'TROLLBERGET', description: 'Sit/stand support, Glose black', price: 149.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 18, rating: REVIEW_DATA[18].average, reviews: REVIEW_DATA[18].count, image: imgStr(18), close: closeGen(18), loose: looseGen(18) } } },
  { replaceOne: { filter: { id: 19 }, upsert: true, replacement: { name: 'KOLON', description: 'Floor protector, 47 1/4x39 3/8 "', price: 24.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 19, rating: REVIEW_DATA[19].average, reviews: REVIEW_DATA[19].count, image: imgStr(19), close: closeGen(19), loose: looseGen(19) } } },
  { replaceOne: { filter: { id: 20 }, upsert: true, replacement: { name: 'MALINDA', description: 'Chair pad, light beige, 16/14x15x3 "', price: 4.49, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 20, rating: REVIEW_DATA[20].average, reviews: REVIEW_DATA[20].count, image: imgStr(20), close: closeGen(20), loose: looseGen(20) } } },
  { replaceOne: { filter: { id: 21 }, upsert: true, replacement: { name: 'GONATT', description: 'Crib, light gray, 27 1/2x52 "', price: 199.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 21, rating: REVIEW_DATA[21].average, reviews: REVIEW_DATA[21].count, image: imgStr(21), close: closeGen(21), loose: looseGen(21) } } },
  { replaceOne: { filter: { id: 22 }, upsert: true, replacement: { name: 'NORDLI', description: 'Bed with headboard and storage, white, King', price: 649.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 22, rating: REVIEW_DATA[22].average, reviews: REVIEW_DATA[22].count, image: imgStr(22), close: closeGen(22), loose: looseGen(22) } } },
  { replaceOne: { filter: { id: 23 }, upsert: true, replacement: { name: 'SAGSTUA', description: 'Bed frame, black, Full', price: 149.00, isOnSale: true, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 23, rating: REVIEW_DATA[23].average, reviews: REVIEW_DATA[23].count, image: imgStr(23), close: closeGen(23), loose: looseGen(23) } } },
  { replaceOne: { filter: { id: 24 }, upsert: true, replacement: { name: 'GODFJORD', description: 'Bed frame, gray, Queen', price: 419.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 24, rating: REVIEW_DATA[24].average, reviews: REVIEW_DATA[24].count, image: imgStr(24), close: closeGen(24), loose: looseGen(24) } } },
  { replaceOne: { filter: { id: 25 }, upsert: true, replacement: { name: 'SONGESAND', description: 'Bed frame with 4 storage boxes, brown, Full/Double', price: 249.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 25, rating: REVIEW_DATA[25].average, reviews: REVIEW_DATA[25].count, image: imgStr(25), close: closeGen(25), loose: looseGen(25) } } },
  { replaceOne: { filter: { id: 26 }, upsert: true, replacement: { name: 'DELAKTIG', description: 'Bed frame/headboard/2 side tables, aluminum, rattan, Queen', price: 599.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 26, rating: REVIEW_DATA[26].average, reviews: REVIEW_DATA[26].count, image: imgStr(26), close: closeGen(26), loose: looseGen(26) } } },
  { replaceOne: { filter: { id: 27 }, upsert: true, replacement: { name: 'HEMNES', description: 'Bed frame with 4 storage boxes, dark gray stained, Leirsund, Queen', price: 469.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 27, rating: REVIEW_DATA[27].average, reviews: REVIEW_DATA[27].count, image: imgStr(27), close: closeGen(27), loose: looseGen(27) } } },
  { replaceOne: { filter: { id: 28 }, upsert: true, replacement: { name: 'ESPEVÄR', description: 'Divan bed, Mausund medium firm, natural, Queen', price: 1129.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 28, rating: REVIEW_DATA[28].average, reviews: REVIEW_DATA[28].count, image: imgStr(28), close: closeGen(28), loose: looseGen(28) } } },
  { replaceOne: { filter: { id: 29 }, upsert: true, replacement: { name: 'UTÅKER', description: 'Stackable bed with 2 mattresses, pine, Husvika, Twin', price: 389.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 29, rating: REVIEW_DATA[29].average, reviews: REVIEW_DATA[29].count, image: imgStr(29), close: closeGen(29), loose: looseGen(29) } } },
  { replaceOne: { filter: { id: 30 }, upsert: true, replacement: { name: 'KVALFJORD', description: 'Bed frame, Risane natural, Luröy, Queen', price: 649.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 30, rating: REVIEW_DATA[30].average, reviews: REVIEW_DATA[30].count, image: imgStr(30), close: closeGen(30), loose: looseGen(30) } } },
  { replaceOne: { filter: { id: 31 }, upsert: true, replacement: { name: 'NEIDEN', description: 'Bed frame, birch pine, Luröy, Full', price: 99.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 31, rating: REVIEW_DATA[31].average, reviews: REVIEW_DATA[31].count, image: imgStr(31), close: closeGen(31), loose: looseGen(31) } } },
  { replaceOne: { filter: { id: 32 }, upsert: true, replacement: { name: 'HEMMAHOS', description: 'Children\'s tent, caravan', price: 34.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 32, rating: REVIEW_DATA[32].average, reviews: REVIEW_DATA[32].count, image: imgStr(32), close: closeGen(32), loose: looseGen(32) } } },
  { replaceOne: { filter: { id: 33 }, upsert: true, replacement: { name: 'LÖVA', description: 'Bed canopy, green', price: 14.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 33, rating: REVIEW_DATA[33].average, reviews: REVIEW_DATA[33].count, image: imgStr(33), close: closeGen(33), loose: looseGen(33) } } },
  { replaceOne: { filter: { id: 34 }, upsert: true, replacement: { name: 'MINNEN', description: 'Ext bed frame with slatted bed base, white, 38 1/4x74 3/4 "', price: 99.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 34, rating: REVIEW_DATA[34].average, reviews: REVIEW_DATA[34].count, image: imgStr(34), close: closeGen(34), loose: looseGen(34) } } },
  { replaceOne: { filter: { id: 35 }, upsert: true, replacement: { name: 'SLÄKT', description: 'Bed frame w/storage+slatted bedbase, white, Twin', price: 279.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 35, rating: REVIEW_DATA[35].average, reviews: REVIEW_DATA[35].count, image: imgStr(35), close: closeGen(35), loose: looseGen(35) } } },
  { replaceOne: { filter: { id: 36 }, upsert: true, replacement: { name: 'VITVAL', description: 'Loft bed frame with desk top, white, light gray, Twin', price: 229.00, isOnSale: false, isFamilyPriced: false, isNewItem: true, hasOptions: false, id: 36, rating: REVIEW_DATA[36].average, reviews: REVIEW_DATA[36].count, image: imgStr(36), close: closeGen(36), loose: looseGen(36) } } },
  { replaceOne: { filter: { id: 37 }, upsert: true, replacement: { name: 'TUFFING', description: 'Bunk bed frame, dark gray, Twin', price: 119.00, isOnSale: true, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 37, rating: REVIEW_DATA[37].average, reviews: REVIEW_DATA[37].count, image: imgStr(37), close: closeGen(37), loose: looseGen(37) } } },
  { replaceOne: { filter: { id: 38 }, upsert: true, replacement: { name: 'NORDDAL', description: 'Bunk bed frame, black-brown, Twin', price: 299.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 38, rating: REVIEW_DATA[38].average, reviews: REVIEW_DATA[38].count, image: imgStr(38), close: closeGen(38), loose: looseGen(38) } } },
  { replaceOne: { filter: { id: 39 }, upsert: true, replacement: { name: 'MYDAL', description: 'Bunk bed frame, pine, Twin', price: 179.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 39, rating: REVIEW_DATA[39].average, reviews: REVIEW_DATA[39].count, image: imgStr(39), close: closeGen(39), loose: looseGen(39) } } },
  { replaceOne: { filter: { id: 40 }, upsert: true, replacement: { name: 'ALLEMANSRÄTTEN', description: 'Vegetable balls, frozen, vegan 100% vegetables', price: 7.99, isOnSale: true, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 40, rating: REVIEW_DATA[40].average, reviews: REVIEW_DATA[40].count, image: imgStr(40), close: closeGen(40), loose: looseGen(40) } } },
  { replaceOne: { filter: { id: 41 }, upsert: true, replacement: { name: 'HAMNSKÄR', description: 'Bath faucet with strainer, brass brass color', price: 89.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 41, rating: REVIEW_DATA[41].average, reviews: REVIEW_DATA[41].count, image: imgStr(41), close: closeGen(41), loose: looseGen(41) } } },
  { replaceOne: { filter: { id: 42 }, upsert: true, replacement: { name: 'LILLSVAN', description: 'Bath faucet with strainer, chrome plated', price: 39.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 42, rating: REVIEW_DATA[42].average, reviews: REVIEW_DATA[42].count, image: imgStr(42), close: closeGen(42), loose: looseGen(42) } } },
  { replaceOne: { filter: { id: 43 }, upsert: true, replacement: { name: 'VOXNAN', description: 'Faucet, tall, chrome plated', price: 89.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 43, rating: REVIEW_DATA[43].average, reviews: REVIEW_DATA[43].count, image: imgStr(43), close: closeGen(43), loose: looseGen(43) } } },
  { replaceOne: { filter: { id: 44 }, upsert: true, replacement: { name: 'RUNSKÄR', description: 'Bath faucet with strainer, chrome plated', price: 49.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 44, rating: REVIEW_DATA[44].average, reviews: REVIEW_DATA[44].count, image: imgStr(44), close: closeGen(44), loose: looseGen(44) } } },
  { replaceOne: { filter: { id: 45 }, upsert: true, replacement: { name: 'STOCKHOLM', description: 'Mirror, walnut veneer, 23 5/8 "', price: 59.99, isOnSale: false, isFamilyPriced: false, isNewItem: true, hasOptions: false, id: 45, rating: REVIEW_DATA[45].average, reviews: REVIEW_DATA[45].count, image: imgStr(45), close: closeGen(45), loose: looseGen(45) } } },
  { replaceOne: { filter: { id: 46 }, upsert: true, replacement: { name: 'ISFJORDEN', description: 'Floor mirror, black-brown stain, 18 1/2x71 5/8 "', price: 149.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 46, rating: REVIEW_DATA[46].average, reviews: REVIEW_DATA[46].count, image: imgStr(46), close: closeGen(46), loose: looseGen(46) } } },
  { replaceOne: { filter: { id: 47 }, upsert: true, replacement: { name: 'KAITUM', description: 'Mirror with built-in light, battery operated, 7 7/8 "', price: 29.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 47, rating: REVIEW_DATA[47].average, reviews: REVIEW_DATA[47].count, image: imgStr(47), close: closeGen(47), loose: looseGen(47) } } },
  { replaceOne: { filter: { id: 48 }, upsert: true, replacement: { name: 'IKORNNES', description: 'Table mirror, ash, 10 5/8x15 3/4 "', price: 29.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 48, rating: REVIEW_DATA[48].average, reviews: REVIEW_DATA[48].count, image: imgStr(48), close: closeGen(48), loose: looseGen(48) } } },
  { replaceOne: { filter: { id: 49 }, upsert: true, replacement: { name: 'GODMORGON', description: 'Box with lid, set of 5, smoked, 9 ½x7 ¾x4 "', price: 14.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 49, rating: REVIEW_DATA[49].average, reviews: REVIEW_DATA[49].count, image: imgStr(49), close: closeGen(49), loose: looseGen(49) } } },
  { replaceOne: { filter: { id: 50 }, upsert: true, replacement: { name: 'SAXBORGA', description: 'Jar with lid and tray, set of 5, glass cork', price: 14.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 50, rating: REVIEW_DATA[50].average, reviews: REVIEW_DATA[50].count, image: imgStr(50), close: closeGen(50), loose: looseGen(50) } } },
  { replaceOne: { filter: { id: 51 }, upsert: true, replacement: { name: 'SKÅDIS', description: 'Pegboard combination, white, 22x22 "', price: 35.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 51, rating: REVIEW_DATA[51].average, reviews: REVIEW_DATA[51].count, image: imgStr(51), close: closeGen(51), loose: looseGen(51) } } },
  { replaceOne: { filter: { id: 52 }, upsert: true, replacement: { name: 'LOCKIG', description: 'Children\'s potty, green white, green', price: 12.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 52, rating: REVIEW_DATA[52].average, reviews: REVIEW_DATA[52].count, image: imgStr(52), close: closeGen(52), loose: looseGen(52) } } },
  { replaceOne: { filter: { id: 53 }, upsert: true, replacement: { name: 'SAXBORGA', description: 'Storage box with mirrored lid, plastic cork, 9 ½x6 ¾ "', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 53, rating: REVIEW_DATA[53].average, reviews: REVIEW_DATA[53].count, image: imgStr(53), close: closeGen(53), loose: looseGen(53) } } },
  { replaceOne: { filter: { id: 54 }, upsert: true, replacement: { name: 'LÅDDAN', description: '6-piece storage board set, with suction cups, assorted colors mixed colors', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 54, rating: REVIEW_DATA[54].average, reviews: REVIEW_DATA[54].count, image: imgStr(54), close: closeGen(54), loose: looseGen(54) } } },
  { replaceOne: { filter: { id: 55 }, upsert: true, replacement: { name: 'DOPPA', description: 'Bathtub mat, light gray, 13x33 "', price: 7.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 55, rating: REVIEW_DATA[55].average, reviews: REVIEW_DATA[55].count, image: imgStr(55), close: closeGen(55), loose: looseGen(55) } } },
  { replaceOne: { filter: { id: 56 }, upsert: true, replacement: { name: 'TISKEN', description: 'Basket with suction cup, white', price: 7.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 56, rating: REVIEW_DATA[56].average, reviews: REVIEW_DATA[56].count, image: imgStr(56), close: closeGen(56), loose: looseGen(56) } } },
  { replaceOne: { filter: { id: 57 }, upsert: true, replacement: { name: 'LILLÅNGEN', description: 'Sink, white, 16 1/8x16x5 1/8 "', price: 80.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 57, rating: REVIEW_DATA[57].average, reviews: REVIEW_DATA[57].count, image: imgStr(57), close: closeGen(57), loose: looseGen(57) } } },
  { replaceOne: { filter: { id: 58 }, upsert: true, replacement: { name: 'GUTVIKEN', description: 'Countertop sink, white, 11 3/8x15 3/8 "', price: 60.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 58, rating: REVIEW_DATA[58].average, reviews: REVIEW_DATA[58].count, image: imgStr(58), close: closeGen(58), loose: looseGen(58) } } },
  { replaceOne: { filter: { id: 59 }, upsert: true, replacement: { name: 'TÖRNVIKEN', description: 'Countertop sink, white, 17 3/4 "', price: 79.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 59, rating: REVIEW_DATA[59].average, reviews: REVIEW_DATA[59].count, image: imgStr(59), close: closeGen(59), loose: looseGen(59) } } },
  { replaceOne: { filter: { id: 60 }, upsert: true, replacement: { name: 'ODENSVIK', description: 'Double bowl sink, 40 1/2x19 1/4x2 3/8 "', price: 140.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 60, rating: REVIEW_DATA[60].average, reviews: REVIEW_DATA[60].count, image: imgStr(60), close: closeGen(60), loose: looseGen(60) } } },
  { replaceOne: { filter: { id: 61 }, upsert: true, replacement: { name: 'DUKTIG', description: '7-piece toy baking set', price: 11.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 61, rating: REVIEW_DATA[61].average, reviews: REVIEW_DATA[61].count, image: imgStr(61), close: closeGen(61), loose: looseGen(61) } } },
  { replaceOne: { filter: { id: 62 }, upsert: true, replacement: { name: 'LILLABO', description: '45-piece train set with track', price: 29.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 62, rating: REVIEW_DATA[62].average, reviews: REVIEW_DATA[62].count, image: imgStr(62), close: closeGen(62), loose: looseGen(62) } } },
  { replaceOne: { filter: { id: 63 }, upsert: true, replacement: { name: 'STORABO', description: 'Rug, green, 29 1/2x52 3/8 "', price: 9.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 63, rating: REVIEW_DATA[63].average, reviews: REVIEW_DATA[63].count, image: imgStr(63), close: closeGen(63), loose: looseGen(63) } } },
  { replaceOne: { filter: { id: 64 }, upsert: true, replacement: { name: 'VURM', description: '4-bottle wine rack, stainless steel', price: 12.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 64, rating: REVIEW_DATA[64].average, reviews: REVIEW_DATA[64].count, image: imgStr(64), close: closeGen(64), loose: looseGen(64) } } },
  { replaceOne: { filter: { id: 65 }, upsert: true, replacement: { name: 'KUNGSFORS', description: 'Dish drainer', price: 39.99, isOnSale: false, isFamilyPriced: false, isNewItem: true, hasOptions: false, id: 65, rating: REVIEW_DATA[65].average, reviews: REVIEW_DATA[65].count, image: imgStr(65), close: closeGen(65), loose: looseGen(65) } } },
  { replaceOne: { filter: { id: 66 }, upsert: true, replacement: { name: 'ORDNING', description: 'Utensil holder, stainless steel, 7 1/8 "', price: 3.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 66, rating: REVIEW_DATA[66].average, reviews: REVIEW_DATA[66].count, image: imgStr(66), close: closeGen(66), loose: looseGen(66) } } },
  { replaceOne: { filter: { id: 67 }, upsert: true, replacement: { name: 'TORKAD', description: 'Papertowel holder, silver color', price: 2.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 67, rating: REVIEW_DATA[67].average, reviews: REVIEW_DATA[67].count, image: imgStr(67), close: closeGen(67), loose: looseGen(67) } } },
  { replaceOne: { filter: { id: 68 }, upsert: true, replacement: { name: 'IDEALISK', description: 'Corkscrew, silver color, matte', price: 2.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 68, rating: REVIEW_DATA[68].average, reviews: REVIEW_DATA[68].count, image: imgStr(68), close: closeGen(68), loose: looseGen(68) } } },
  { replaceOne: { filter: { id: 69 }, upsert: true, replacement: { name: 'JÄMFÖRA', description: 'Knife block with 3 knives, black', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 69, rating: REVIEW_DATA[69].average, reviews: REVIEW_DATA[69].count, image: imgStr(69), close: closeGen(69), loose: looseGen(69) } } },
  { replaceOne: { filter: { id: 70 }, upsert: true, replacement: { name: 'ÄNDLIG', description: '3-piece knife set, light gray, white', price: 7.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 70, rating: REVIEW_DATA[70].average, reviews: REVIEW_DATA[70].count, image: imgStr(70), close: closeGen(70), loose: looseGen(70) } } },
  { replaceOne: { filter: { id: 71 }, upsert: true, replacement: { name: 'FÖRDUBBLA', description: '2-piece knife set, gray', price: 2.99, isOnSale: true, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 71, rating: REVIEW_DATA[71].average, reviews: REVIEW_DATA[71].count, image: imgStr(71), close: closeGen(71), loose: looseGen(71) } } },
  { replaceOne: { filter: { id: 72 }, upsert: true, replacement: { name: 'FÖRSLAG', description: '3-piece knife set', price: 9.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 72, rating: REVIEW_DATA[72].average, reviews: REVIEW_DATA[72].count, image: imgStr(72), close: closeGen(72), loose: looseGen(72) } } },
  { replaceOne: { filter: { id: 73 }, upsert: true, replacement: { name: 'VÖRDA', description: '3-piece knife set', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 73, rating: REVIEW_DATA[73].average, reviews: REVIEW_DATA[73].count, image: imgStr(73), close: closeGen(73), loose: looseGen(73) } } },
  { replaceOne: { filter: { id: 74 }, upsert: true, replacement: { name: 'DRAGON', description: '20-piece flatware set, stainless steel', price: 12.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 74, rating: REVIEW_DATA[74].average, reviews: REVIEW_DATA[74].count, image: imgStr(74), close: closeGen(74), loose: looseGen(74) } } },
  { replaceOne: { filter: { id: 75 }, upsert: true, replacement: { name: 'MATLUST', description: 'Chopping board, green/white, 13 ½x9 ½ "', price: 5.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 75, rating: REVIEW_DATA[75].average, reviews: REVIEW_DATA[75].count, image: imgStr(75), close: closeGen(75), loose: looseGen(75) } } },
  { replaceOne: { filter: { id: 76 }, upsert: true, replacement: { name: 'SKYDD', description: 'Wood treatment oil, indoor use, 17 oz', price: 5.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 76, rating: REVIEW_DATA[76].average, reviews: REVIEW_DATA[76].count, image: imgStr(76), close: closeGen(76), loose: looseGen(76) } } },
  { replaceOne: { filter: { id: 77 }, upsert: true, replacement: { name: 'APTITLIG', description: 'Butcher block, bamboo, 17 ¾x14 ¼ "', price: 19.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 77, rating: REVIEW_DATA[77].average, reviews: REVIEW_DATA[77].count, image: imgStr(77), close: closeGen(77), loose: looseGen(77) } } },
  { replaceOne: { filter: { id: 78 }, upsert: true, replacement: { name: 'GRUNKA', description: '4-piece kitchen utensil set, stainless steel', price: 7.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 78, rating: REVIEW_DATA[78].average, reviews: REVIEW_DATA[78].count, image: imgStr(78), close: closeGen(78), loose: looseGen(78) } } },
  { replaceOne: { filter: { id: 79 }, upsert: true, replacement: { name: 'GUBBRÖRA', description: 'Rubber spatula, green/pink red/green, blue/white', price: 1.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 79, rating: REVIEW_DATA[79].average, reviews: REVIEW_DATA[79].count, image: imgStr(79), close: closeGen(79), loose: looseGen(79) } } },
  { replaceOne: { filter: { id: 80 }, upsert: true, replacement: { name: 'JÄMFÖRLIG', description: 'Hand held whisk, black, red', price: 12.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 80, rating: REVIEW_DATA[80].average, reviews: REVIEW_DATA[80].count, image: imgStr(80), close: closeGen(80), loose: looseGen(80) } } },
  { replaceOne: { filter: { id: 81 }, upsert: true, replacement: { name: 'KÖTTBULLAR', description: 'Meatballs, frozen', price: 7.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 81, rating: REVIEW_DATA[81].average, reviews: REVIEW_DATA[81].count, image: imgStr(81), close: closeGen(81), loose: looseGen(81) } } },
  { replaceOne: { filter: { id: 82 }, upsert: true, replacement: { name: 'FANBYN', description: 'Bar table and 4 bar stools, white, white', price: 525.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 82, rating: REVIEW_DATA[82].average, reviews: REVIEW_DATA[82].count, image: imgStr(82), close: closeGen(82), loose: looseGen(82) } } },
  { replaceOne: { filter: { id: 83 }, upsert: true, replacement: { name: 'FANBYN', description: 'Bar stool with backrest, white, 25 1/4 "', price: 89.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 83, rating: REVIEW_DATA[83].average, reviews: REVIEW_DATA[83].count, image: imgStr(83), close: closeGen(83), loose: looseGen(83) } } },
  { replaceOne: { filter: { id: 84 }, upsert: true, replacement: { name: 'FRÖSÖN/DUVHOLMEN', description: 'Seat pad, outdoor, beige, 24 3/8x24 3/8 "', price: 35.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 84, rating: REVIEW_DATA[84].average, reviews: REVIEW_DATA[84].count, image: imgStr(84), close: closeGen(84), loose: looseGen(84) } } },
  { replaceOne: { filter: { id: 85 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Drop-leaf table, outdoor, brown stained brown, 55 1/8/78 3/4/102 3/8x30 3/4 "', price: 149.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 85, rating: REVIEW_DATA[85].average, reviews: REVIEW_DATA[85].count, image: imgStr(85), close: closeGen(85), loose: looseGen(85) } } },
  { replaceOne: { filter: { id: 86 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Bench, outdoor, brown stained brown, 44 7/8 "', price: 65.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 86, rating: REVIEW_DATA[86].average, reviews: REVIEW_DATA[86].count, image: imgStr(86), close: closeGen(86), loose: looseGen(86) } } },
  { replaceOne: { filter: { id: 87 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Chaise, brown stained brown', price: 129.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 87, rating: REVIEW_DATA[87].average, reviews: REVIEW_DATA[87].count, image: imgStr(87), close: closeGen(87), loose: looseGen(87) } } },
  { replaceOne: { filter: { id: 88 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Reclining chair, outdoor, brown foldable brown stained brown', price: 65.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 88, rating: REVIEW_DATA[88].average, reviews: REVIEW_DATA[88].count, image: imgStr(88), close: closeGen(88), loose: looseGen(88) } } },
  { replaceOne: { filter: { id: 89 }, upsert: true, replacement: { name: 'FRÖSÖN/DUVHOLMEN', description: 'Back cushion, outdoor, beige, 24 3/8x17 3/8 "', price: 25.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 89, rating: REVIEW_DATA[89].average, reviews: REVIEW_DATA[89].count, image: imgStr(89), close: closeGen(89), loose: looseGen(89) } } },
  { replaceOne: { filter: { id: 90 }, upsert: true, replacement: { name: 'HAVSTEN', description: 'Loveseat, in/outdoor, with open end without armrests, beige, 64 5/8x37x35 3/8 "', price: 490.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 90, rating: REVIEW_DATA[90].average, reviews: REVIEW_DATA[90].count, image: imgStr(90), close: closeGen(90), loose: looseGen(90) } } },
  { replaceOne: { filter: { id: 91 }, upsert: true, replacement: { name: 'BROMMÖ', description: 'Chaise, outdoor, black brown stained, brown', price: 59.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 91, rating: REVIEW_DATA[91].average, reviews: REVIEW_DATA[91].count, image: imgStr(91), close: closeGen(91), loose: looseGen(91) } } },
  { replaceOne: { filter: { id: 92 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Armchair, outdoor, brown stained brown', price: 65.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 92, rating: REVIEW_DATA[92].average, reviews: REVIEW_DATA[92].count, image: imgStr(92), close: closeGen(92), loose: looseGen(92) } } },
  { replaceOne: { filter: { id: 93 }, upsert: true, replacement: { name: 'HÅLLÖ', description: 'Seat pad, outdoor, black, 24x24 "', price: 25.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 93, rating: REVIEW_DATA[93].average, reviews: REVIEW_DATA[93].count, image: imgStr(93), close: closeGen(93), loose: looseGen(93) } } },
  { replaceOne: { filter: { id: 94 }, upsert: true, replacement: { name: 'SOLLERÖN', description: '3-seat modular sofa, outdoor, with footstool brown brown, Frösön/Duvholmen beige, 87 3/4x56 3/4x34 5/8 "', price: 750.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 94, rating: REVIEW_DATA[94].average, reviews: REVIEW_DATA[94].count, image: imgStr(94), close: closeGen(94), loose: looseGen(94) } } },
  { replaceOne: { filter: { id: 95 }, upsert: true, replacement: { name: 'ÄPPLARÖ', description: 'Table+2 benches, outdoor, brown stained', price: 309.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 95, rating: REVIEW_DATA[95].average, reviews: REVIEW_DATA[95].count, image: imgStr(95), close: closeGen(95), loose: looseGen(95) } } },
  { replaceOne: { filter: { id: 96 }, upsert: true, replacement: { name: 'TÄRNÖ', description: 'Chair, outdoor, foldable acacia black, steel gray-brown stained light brown stained', price: 15.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 96, rating: REVIEW_DATA[96].average, reviews: REVIEW_DATA[96].count, image: imgStr(96), close: closeGen(96), loose: looseGen(96) } } },
  { replaceOne: { filter: { id: 97 }, upsert: true, replacement: { name: 'TOSTERÖ', description: 'Cover for outdoor furniture, sofa, black, 102 3/8x65 "', price: 49.99, isOnSale: false, isFamilyPriced: false, isNewItem: true, hasOptions: true, id: 97, rating: REVIEW_DATA[97].average, reviews: REVIEW_DATA[97].count, image: imgStr(97), close: closeGen(97), loose: looseGen(97) } } },
  { replaceOne: { filter: { id: 98 }, upsert: true, replacement: { name: 'KLÖVEN', description: '4-seat conversation set, outdoor, brown stained, Frösön/Duvholmen beige', price: 756.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 98, rating: REVIEW_DATA[98].average, reviews: REVIEW_DATA[98].count, image: imgStr(98), close: closeGen(98), loose: looseGen(98) } } },
  { replaceOne: { filter: { id: 99 }, upsert: true, replacement: { name: 'SOLLERÖN', description: '4-seat conversation set, outdoor, dark gray, Frösön/Duvholmen beige', price: 1115.00, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: true, id: 99, rating: REVIEW_DATA[99].average, reviews: REVIEW_DATA[99].count, image: imgStr(99), close: closeGen(99), loose: looseGen(99) } } },
  { replaceOne: { filter: { id: 100 }, upsert: true, replacement: { name: 'OTTERÖN / INNERSKÄR', description: 'Pouffe, in/outdoor, blue, 18 7/8 "', price: 59.99, isOnSale: false, isFamilyPriced: false, isNewItem: false, hasOptions: false, id: 100, rating: REVIEW_DATA[100].average, reviews: REVIEW_DATA[100].count, image: imgStr(100), close: closeGen(100), loose: looseGen(100) } } },
], (err) => {
  if (err) {
    console.log(err);
  } else {
    console.log('Done');
    Product.createIndexes();
  }
});
